### ISSUE TITLE
Regarding the dataset

### ISSUE THREAD

**Issue by Filco306** [fYYw/fingerprinting#1]
Hello! I was wondering, is the dataset used in your paper available to download somewhere? Thank you in advance :)

**Comment by fYYw** [comment]
Hi Filip,

I think you can download the dataset from this place: https://1drv.ms/u/s!ArmA0im3WhtLi8okbgq49n8VOYe3kQ?e=aUXzyc

Let me know if the link is working or not.

**Comment by Filco306** [comment]
Hmm, that was strange; I saw it for a quick second, but then it forced me to login, and post-login I could not see it. Maybe there is a problem with the privileges?

**Comment by Filco306** [comment]
Okay, it started download ing now :)

**Comment by fYYw** [comment]
Great! Glad to know it.
